// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3obEthLGYL9w0Dln4QeKYuoJY1XIMEgY',
    appId: '1:949357295578:web:2c664786898b1b5abbf2e3',
    messagingSenderId: '949357295578',
    projectId: 'fizmatapp',
    authDomain: 'fizmatapp.firebaseapp.com',
    storageBucket: 'fizmatapp.firebasestorage.app',
    measurementId: 'G-CW293J5FDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc8lATfV7uOKm6GjNn4RK3J6GOUToe5_Q',
    appId: '1:949357295578:android:014153a784219029bbf2e3',
    messagingSenderId: '949357295578',
    projectId: 'fizmatapp',
    storageBucket: 'fizmatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3w9CeR6CUTZDT6XeOj77vjVX8v4lApUI',
    appId: '1:949357295578:ios:b7f44f1d52b259b8bbf2e3',
    messagingSenderId: '949357295578',
    projectId: 'fizmatapp',
    storageBucket: 'fizmatapp.firebasestorage.app',
    iosBundleId: 'com.fizmat.fizmatApp',
  );

}